# Generated by Django 5.0.4 on 2024-04-27 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adsb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('UpTime', models.CharField(max_length=50, null=True)),
                ('FrameRate', models.CharField(max_length=50, null=True)),
                ('Connected', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ctc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('TimeLabel', models.CharField(max_length=50, null=True)),
                ('TimeLabelIntegrated', models.CharField(max_length=50, null=True)),
                ('NRXIntegrated', models.CharField(max_length=50, null=True)),
                ('RXValues', models.JSONField(null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JsonLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('AllData', models.JSONField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JsonShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('TX', models.JSONField()),
                ('RX', models.JSONField()),
                ('Operation', models.JSONField()),
                ('AllPCs', models.JSONField()),
                ('SNMPAgents', models.JSONField()),
                ('SherkatNet', models.JSONField()),
                ('RXNet', models.JSONField()),
                ('TxNet', models.JSONField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('IP', models.CharField(max_length=50, null=True)),
                ('NLayer', models.CharField(max_length=50, null=True)),
                ('AX', models.CharField(max_length=50, null=True)),
                ('AY', models.CharField(max_length=50, null=True)),
                ('UpTime', models.CharField(max_length=50, null=True)),
                ('Layers', models.JSONField(null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('MemPer', models.CharField(max_length=50, null=True)),
                ('CPULoad', models.CharField(max_length=50, null=True)),
                ('HDDValues', models.JSONField(null=True)),
                ('Cores', models.JSONField(null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SigPrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('ChProps', models.JSONField(null=True)),
                ('TimeLabel', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Snmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Values', models.JSONField(null=True)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
