# Generated by Django 5.0.4 on 2024-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
